
class BangLuong {
    String? nhanSu;
    String? thang;
    String? nam;
    String? phongBan;
    String? toCongTac;
    String? hoTen;
    String? chucVu;
    String? stt;
    String? hsl;
    String? luongCb;
    String? luongBhxh;
    String? pcLuong;
    String? pcTrachNhiem;
    String? pcDienThoai;
    String? pcXangXe;
    String? pcAnCa;
    String? mucLuong;
    String? congDinhMuc;
    String? ngayCong;
    String? nghiLe;
    String? nghiPhep;
    String? thuongNs;
    String? tongLuongCu;
    String? tamUngNs;
    String? conLaiNs;
    String? luongDieuChinh;
    String? luongNgay;
    String? ngayCong2;
    String? mucLuong2;
    String? luongCb2;
    String? pcTrachNhiem2;
    String? pcDienThoai2;
    String? pcXangXe2;
    String? pcAnCa2;
    String? thuongNs2;
    String? tongLuong2;
    String? tamUngNs2;
    String? conLaiNs2;
    String? luongDieuChinh2;
    String? luongNgay2;
    String? tongCong;
    String? tongLuong;
    String? bhxhCongTy;
    String? bhxhNhanSu;
    String? tongBhxh;
    String? bhytCongTy;
    String? bhytNhanSu;
    String? tongBhyt;
    String? bhtnCongTy;
    String? bhtnNhanSu;
    String? tongBhtn;
    String? tongBhCongTy;
    String? tongBhNhanSu;
    String? tongBaoHiem;
    String? tienCongDoanCt;
    String? tienCongDoanNs;
    String? tongCongDoan;
    String? tienThemGio;
    String? tienNsld;
    String? dcTang;
    String? dcGiam;
    String? tongLuongDieuChinh;
    String? luongSauBaoHiem;
    String? soNguoiGiamTru;
    String? giamTruGiaCanh;
    String? thuNhapChiuThue;
    String? thueThuNhap;
    String? luongSauThue;
    String? thucLinh;
    String? dongPhuc;
    String? thuongLe;
    String? nghiMat;
    String? khamSk;
    String? daoTao;
    String? tongNsld;
    String? thuongTetNd;
    String? thuongTetDl;
    String? cpKhac;
    String? giamTruNld;

    BangLuong({this.nhanSu, this.thang, this.nam, this.phongBan, this.toCongTac, this.hoTen, this.chucVu, this.stt, this.hsl, this.luongCb, this.luongBhxh, this.pcLuong, this.pcTrachNhiem, this.pcDienThoai, this.pcXangXe, this.pcAnCa, this.mucLuong, this.congDinhMuc, this.ngayCong, this.nghiLe, this.nghiPhep, this.thuongNs, this.tongLuongCu, this.tamUngNs, this.conLaiNs, this.luongDieuChinh, this.luongNgay, this.ngayCong2, this.mucLuong2, this.luongCb2, this.pcTrachNhiem2, this.pcDienThoai2, this.pcXangXe2, this.pcAnCa2, this.thuongNs2, this.tongLuong2, this.tamUngNs2, this.conLaiNs2, this.luongDieuChinh2, this.luongNgay2, this.tongCong, this.tongLuong, this.bhxhCongTy, this.bhxhNhanSu, this.tongBhxh, this.bhytCongTy, this.bhytNhanSu, this.tongBhyt, this.bhtnCongTy, this.bhtnNhanSu, this.tongBhtn, this.tongBhCongTy, this.tongBhNhanSu, this.tongBaoHiem, this.tienCongDoanCt, this.tienCongDoanNs, this.tongCongDoan, this.tienThemGio, this.tienNsld, this.dcTang, this.dcGiam, this.tongLuongDieuChinh, this.luongSauBaoHiem, this.soNguoiGiamTru, this.giamTruGiaCanh, this.thuNhapChiuThue, this.thueThuNhap, this.luongSauThue, this.thucLinh, this.dongPhuc, this.thuongLe, this.nghiMat, this.khamSk, this.daoTao, this.tongNsld, this.thuongTetNd, this.thuongTetDl, this.cpKhac, this.giamTruNld});

    BangLuong.fromJson(Map<String, dynamic> json) {
        nhanSu = json["NhanSu"];
        thang = json["Thang"];
        nam = json["Nam"];
        phongBan = json["PhongBan"];
        toCongTac = json["ToCongTac"];
        hoTen = json["HoTen"];
        chucVu = json["ChucVu"];
        stt = json["STT"];
        hsl = json["HSL"];
        luongCb = json["LuongCB"];
        luongBhxh = json["LuongBHXH"];
        pcLuong = json["PC_Luong"];
        pcTrachNhiem = json["PC_TrachNhiem"];
        pcDienThoai = json["PC_DienThoai"];
        pcXangXe = json["PC_XangXe"];
        pcAnCa = json["PC_AnCa"];
        mucLuong = json["MucLuong"];
        congDinhMuc = json["CongDinhMuc"];
        ngayCong = json["NgayCong"];
        nghiLe = json["NghiLe"];
        nghiPhep = json["NghiPhep"];
        thuongNs = json["ThuongNS"];
        tongLuongCu = json["TongLuongCu"];
        tamUngNs = json["TamUngNS"];
        conLaiNs = json["ConLaiNS"];
        luongDieuChinh = json["LuongDieuChinh"];
        luongNgay = json["LuongNgay"];
        ngayCong2 = json["NgayCong2"];
        mucLuong2 = json["MucLuong2"];
        luongCb2 = json["LuongCB2"];
        pcTrachNhiem2 = json["PC_TrachNhiem2"];
        pcDienThoai2 = json["PC_DienThoai2"];
        pcXangXe2 = json["PC_XangXe2"];
        pcAnCa2 = json["PC_AnCa2"];
        thuongNs2 = json["ThuongNS2"];
        tongLuong2 = json["TongLuong2"];
        tamUngNs2 = json["TamUngNS2"];
        conLaiNs2 = json["ConLaiNS2"];
        luongDieuChinh2 = json["LuongDieuChinh2"];
        luongNgay2 = json["LuongNgay2"];
        tongCong = json["TongCong"];
        tongLuong = json["TongLuong"];
        bhxhCongTy = json["BHXH_CongTy"];
        bhxhNhanSu = json["BHXH_NhanSu"];
        tongBhxh = json["TongBHXH"];
        bhytCongTy = json["BHYT_CongTy"];
        bhytNhanSu = json["BHYT_NhanSu"];
        tongBhyt = json["TongBHYT"];
        bhtnCongTy = json["BHTN_CongTy"];
        bhtnNhanSu = json["BHTN_NhanSu"];
        tongBhtn = json["TongBHTN"];
        tongBhCongTy = json["TongBH_CongTy"];
        tongBhNhanSu = json["TongBH_NhanSu"];
        tongBaoHiem = json["TongBaoHiem"];
        tienCongDoanCt = json["TienCongDoan_CT"];
        tienCongDoanNs = json["TienCongDoan_NS"];
        tongCongDoan = json["TongCongDoan"];
        tienThemGio = json["TienThemGio"];
        tienNsld = json["TienNSLD"];
        dcTang = json["DC_Tang"];
        dcGiam = json["DC_Giam"];
        tongLuongDieuChinh = json["TongLuongDieuChinh"];
        luongSauBaoHiem = json["LuongSauBaoHiem"];
        soNguoiGiamTru = json["SoNguoiGiamTru"];
        giamTruGiaCanh = json["GiamTruGiaCanh"];
        thuNhapChiuThue = json["ThuNhapChiuThue"];
        thueThuNhap = json["ThueThuNhap"];
        luongSauThue = json["LuongSauThue"];
        thucLinh = json["ThucLinh"];
        dongPhuc = json["DongPhuc"];
        thuongLe = json["ThuongLe"];
        nghiMat = json["NghiMat"];
        khamSk = json["KhamSK"];
        daoTao = json["DaoTao"];
        tongNsld = json["TongNSLD"];
        thuongTetNd = json["ThuongTetND"];
        thuongTetDl = json["ThuongTetDL"];
        cpKhac = json["CP_Khac"];
        giamTruNld = json["GiamTruNLD"];
    }

    Map<String, dynamic> toJson() {
        final Map<String, dynamic> _data = <String, dynamic>{};
        _data["NhanSu"] = nhanSu;
        _data["Thang"] = thang;
        _data["Nam"] = nam;
        _data["PhongBan"] = phongBan;
        _data["ToCongTac"] = toCongTac;
        _data["HoTen"] = hoTen;
        _data["ChucVu"] = chucVu;
        _data["STT"] = stt;
        _data["HSL"] = hsl;
        _data["LuongCB"] = luongCb;
        _data["LuongBHXH"] = luongBhxh;
        _data["PC_Luong"] = pcLuong;
        _data["PC_TrachNhiem"] = pcTrachNhiem;
        _data["PC_DienThoai"] = pcDienThoai;
        _data["PC_XangXe"] = pcXangXe;
        _data["PC_AnCa"] = pcAnCa;
        _data["MucLuong"] = mucLuong;
        _data["CongDinhMuc"] = congDinhMuc;
        _data["NgayCong"] = ngayCong;
        _data["NghiLe"] = nghiLe;
        _data["NghiPhep"] = nghiPhep;
        _data["ThuongNS"] = thuongNs;
        _data["TongLuongCu"] = tongLuongCu;
        _data["TamUngNS"] = tamUngNs;
        _data["ConLaiNS"] = conLaiNs;
        _data["LuongDieuChinh"] = luongDieuChinh;
        _data["LuongNgay"] = luongNgay;
        _data["NgayCong2"] = ngayCong2;
        _data["MucLuong2"] = mucLuong2;
        _data["LuongCB2"] = luongCb2;
        _data["PC_TrachNhiem2"] = pcTrachNhiem2;
        _data["PC_DienThoai2"] = pcDienThoai2;
        _data["PC_XangXe2"] = pcXangXe2;
        _data["PC_AnCa2"] = pcAnCa2;
        _data["ThuongNS2"] = thuongNs2;
        _data["TongLuong2"] = tongLuong2;
        _data["TamUngNS2"] = tamUngNs2;
        _data["ConLaiNS2"] = conLaiNs2;
        _data["LuongDieuChinh2"] = luongDieuChinh2;
        _data["LuongNgay2"] = luongNgay2;
        _data["TongCong"] = tongCong;
        _data["TongLuong"] = tongLuong;
        _data["BHXH_CongTy"] = bhxhCongTy;
        _data["BHXH_NhanSu"] = bhxhNhanSu;
        _data["TongBHXH"] = tongBhxh;
        _data["BHYT_CongTy"] = bhytCongTy;
        _data["BHYT_NhanSu"] = bhytNhanSu;
        _data["TongBHYT"] = tongBhyt;
        _data["BHTN_CongTy"] = bhtnCongTy;
        _data["BHTN_NhanSu"] = bhtnNhanSu;
        _data["TongBHTN"] = tongBhtn;
        _data["TongBH_CongTy"] = tongBhCongTy;
        _data["TongBH_NhanSu"] = tongBhNhanSu;
        _data["TongBaoHiem"] = tongBaoHiem;
        _data["TienCongDoan_CT"] = tienCongDoanCt;
        _data["TienCongDoan_NS"] = tienCongDoanNs;
        _data["TongCongDoan"] = tongCongDoan;
        _data["TienThemGio"] = tienThemGio;
        _data["TienNSLD"] = tienNsld;
        _data["DC_Tang"] = dcTang;
        _data["DC_Giam"] = dcGiam;
        _data["TongLuongDieuChinh"] = tongLuongDieuChinh;
        _data["LuongSauBaoHiem"] = luongSauBaoHiem;
        _data["SoNguoiGiamTru"] = soNguoiGiamTru;
        _data["GiamTruGiaCanh"] = giamTruGiaCanh;
        _data["ThuNhapChiuThue"] = thuNhapChiuThue;
        _data["ThueThuNhap"] = thueThuNhap;
        _data["LuongSauThue"] = luongSauThue;
        _data["ThucLinh"] = thucLinh;
        _data["DongPhuc"] = dongPhuc;
        _data["ThuongLe"] = thuongLe;
        _data["NghiMat"] = nghiMat;
        _data["KhamSK"] = khamSk;
        _data["DaoTao"] = daoTao;
        _data["TongNSLD"] = tongNsld;
        _data["ThuongTetND"] = thuongTetNd;
        _data["ThuongTetDL"] = thuongTetDl;
        _data["CP_Khac"] = cpKhac;
        _data["GiamTruNLD"] = giamTruNld;
        return _data;
    }
}